name: 'Slack Build Notification'
description: 'Sends a build notification to PressCentric/builds channel'

inputs:
  webhook-url:
    description: 'Slack Webhook URL'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        export COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%s)
        export PAYLOAD=$(jq -n \
          --arg commit "$COMMIT_MESSAGE" \
          --arg author ${{ github.actor }} \
          --arg repo "${{ github.repository }}" \
          --arg workflow "${{ github.workflow }}" \
          --arg branch "${{ github.ref }}" \
          --arg sha ${{ github.sha }} \
          --arg build ${{ github.run_number }} \
          --arg color ${{ job.status == 'success' && 'good' || 'danger' }} \
          --arg status ${{ job.status }} \
          '{username:"github",icon_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",attachments:[{mrkdwn_in:["text"],color:$color,author_name:$author,author_link:("http://github.com/" + $author),author_icon:("http://github.com/" + $author + ".png?size=32"),fallback:($repo + " - " + $workflow + " - " + $branch + " - #" + $build + " " + $status),text:("*" + $repo + "* - " + $workflow + " - " + $branch + " - #" + $build + " " + $status + " <https://github.com/" + $repo + "/commit/" + $sha + "/checks|(Open)>"),footer:$commit}]}')
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ inputs.webhook-url }}
      shell: bash

